# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 880)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 140, 51, 21))
        self.label.setMinimumSize(QtCore.QSize(0, 21))
        self.label.setMaximumSize(QtCore.QSize(16777215, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 220, 25, 16))
        self.label_2.setObjectName("label_2")
        self.txtplain = QtWidgets.QLineEdit(self.centralwidget)
        self.txtplain.setGeometry(QtCore.QRect(158, 131, 391, 71))
        self.txtplain.setText("")
        self.txtplain.setObjectName("txtplain")
        self.txtkey = QtWidgets.QLineEdit(self.centralwidget)
        self.txtkey.setGeometry(QtCore.QRect(160, 220, 161, 41))
        self.txtkey.setText("")
        self.txtkey.setObjectName("txtkey")
        self.bntencrypt = QtWidgets.QPushButton(self.centralwidget)
        self.bntencrypt.setGeometry(QtCore.QRect(70, 370, 75, 23))
        self.bntencrypt.setObjectName("bntencrypt")
        self.bntdecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.bntdecrypt.setGeometry(QtCore.QRect(460, 370, 75, 23))
        self.bntdecrypt.setObjectName("bntdecrypt")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 310, 71, 16))
        self.label_3.setObjectName("label_3")
        self.txtcipher = QtWidgets.QLineEdit(self.centralwidget)
        self.txtcipher.setGeometry(QtCore.QRect(160, 290, 391, 61))
        self.txtcipher.setObjectName("txtcipher")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 20, 81, 51))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1028, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PlainText :"))
        self.label_2.setText(_translate("MainWindow", "Key :"))
        self.bntencrypt.setText(_translate("MainWindow", "encrypt"))
        self.bntdecrypt.setText(_translate("MainWindow", "decrypt"))
        self.label_3.setText(_translate("MainWindow", "CipherText:"))
        self.label_4.setText(_translate("MainWindow", "Cipher caesar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
